# Generated by Django 6.0.5 on 2026-07-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_yearlyplan_school_subscription_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='whatsapp_welcome_template_language',
            field=models.CharField(blank=True, default='en', help_text='Language code for welcome template, e.g. en', max_length=20),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='whatsapp_welcome_template_name',
            field=models.CharField(blank=True, default='', help_text='Pre-approved WhatsApp template name for welcome messages', max_length=100),
        ),
    ]
