# Generated by Django 6.0.5 on 2026-07-04 05:32

import schoolapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_whatsappconfig_whatsapp_welcome_template_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='superusersettings',
            name='campus_image',
            field=models.ImageField(blank=True, null=True, upload_to=schoolapp.models.superuser_campus_upload_to),
        ),
        migrations.AddField(
            model_name='superusersettings',
            name='campus_image2',
            field=models.ImageField(blank=True, null=True, upload_to=schoolapp.models.superuser_campus_upload_to),
        ),
        migrations.AddField(
            model_name='superusersettings',
            name='campus_image3',
            field=models.ImageField(blank=True, null=True, upload_to=schoolapp.models.superuser_campus_upload_to),
        ),
    ]
