# Generated by Django 6.0.5 on 2026-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_student_bulk_upload_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='campus_image',
            field=models.ImageField(blank=True, null=True, upload_to='school_campus/'),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='theme_color',
            field=models.CharField(default='#0f766e', help_text='Primary theme color in hex, e.g. #0f766e', max_length=7),
        ),
    ]
