# Generated by Django 6.0.5 on 2026-07-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_superusersettings_campus_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about_us_bullets',
            field=models.TextField(blank=True, default='', help_text='One bullet point per line.'),
        ),
        migrations.AddField(
            model_name='school',
            name='about_us_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='admission_open_session',
            field=models.CharField(blank=True, default='2026-27', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='established_year',
            field=models.CharField(blank=True, default='2004', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='stat_experience',
            field=models.CharField(blank=True, default='22+', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='stat_staff',
            field=models.CharField(blank=True, default='24+', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='stat_students',
            field=models.CharField(blank=True, default='2200+', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_1_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_1_role',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_1_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_2_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_2_role',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_2_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_3_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_3_role',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='school',
            name='testimonial_3_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
