# Generated by Django 6.0.5 on 2026-06-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_school_campus_image_school_motto_school_theme_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='campus_image2',
            field=models.ImageField(blank=True, null=True, upload_to='school_campus/'),
        ),
        migrations.AddField(
            model_name='school',
            name='campus_image3',
            field=models.ImageField(blank=True, null=True, upload_to='school_campus/'),
        ),
    ]
