# Generated by Django 6.0.5 on 2026-06-26 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0006_school_campus_image2_school_campus_image3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('holiday', 'Holiday Notice'), ('fee', 'Fee Submission Reminder'), ('exam', 'Exam Schedule'), ('admission', 'Admission Notice'), ('event', 'School Event'), ('circular', 'Circular')], default='circular', max_length=50)),
                ('publish_date', models.DateField(default=django.utils.timezone.localdate)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public (Login Page)'), ('students', 'Students Only'), ('staff', 'Staff Only')], default='public', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='notifications/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='schoolapp.school')),
            ],
            options={
                'ordering': ['-is_pinned', '-publish_date', '-created_at'],
            },
        ),
    ]
