# Generated by Django 6.0.5 on 2026-06-27 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='theme_color',
            field=models.CharField(default='#2563eb', help_text='Primary theme color in hex, e.g. #2563eb', max_length=7),
        ),
    ]
