# Generated by Django 6.0.5 on 2026-05-18 12:58

import core.session_utils
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fee_per_student', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperUserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(default='SchoolERP', max_length=150)),
                ('superuser_name', models.CharField(blank=True, max_length=150)),
                ('superuser_email', models.EmailField(blank=True, max_length=254)),
                ('superuser_phone', models.CharField(blank=True, max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='software_logos/')),
                ('organization_address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('default_session', models.CharField(blank=True, default='', help_text='Default academic session shown on superuser dashboard and school fee pages.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superuser', 'Super User'), ('school_admin', 'School Admin')], default='school_admin', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SchoolBillingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('academic_session', models.CharField(blank=True, default='', max_length=20)),
                ('payment_date', models.DateField()),
                ('num_students', models.PositiveIntegerField()),
                ('fee_per_student', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_months', models.JSONField(default=list)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_payments', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ExamFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=100)),
                ('academic_session', models.CharField(default=core.session_utils.default_current_academic_session, max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_fees', to='core.schoolclass')),
            ],
            options={
                'ordering': ['exam_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_academic_session', models.CharField(default=core.session_utils.default_current_academic_session, max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('session_start_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='april', max_length=15)),
                ('session_end_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='march', max_length=15)),
                ('billing_start_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='april', max_length=15)),
                ('billing_end_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='march', max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField()),
                ('academic_session', models.CharField(default=core.session_utils.default_current_academic_session, max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('status', models.CharField(choices=[('inactive', 'Transferred'), ('promoted', 'Promoted'), ('fail', 'Fail')], default='active', max_length=20)),
                ('father_name', models.CharField(max_length=120)),
                ('mother_name', models.CharField(default='', max_length=120)),
                ('father_phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Father phone must be exactly 10 digits.')])),
                ('address', models.TextField()),
                ('blood_group', models.CharField(blank=True, default='', max_length=10)),
                ('previous_school', models.CharField(blank=True, default='', max_length=200)),
                ('aadhaar_number', models.CharField(blank=True, default='', max_length=12)),
                ('pen_number', models.CharField(blank=True, default='', max_length=20)),
                ('religion', models.CharField(default='', max_length=100)),
                ('caste', models.CharField(default='', max_length=100)),
                ('admission_date', models.DateField(default=django.utils.timezone.localdate)),
                ('transport_opted', models.BooleanField(default=False)),
                ('transport_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='core.schoolclass')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(editable=False, max_length=20)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('academic_session', models.CharField(blank=True, default='', max_length=20)),
                ('payment_months', models.JSONField(blank=True, default=list)),
                ('exam_fee_items', models.JSONField(blank=True, default=list)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('transport_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('balance_due', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collected_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collected_payments', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='core.student')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(blank=True, editable=False, max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}$', message='Phone must be exactly 10 digits.')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('qualification', models.CharField(help_text='e.g. B.Ed, M.Sc, M.Ed', max_length=150)),
                ('subjects_taught', models.CharField(blank=True, help_text='Comma-separated subjects, e.g. Maths, Science', max_length=255)),
                ('joining_date', models.DateField(default=django.utils.timezone.localdate)),
                ('employment_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract')], default='full_time', max_length=20)),
                ('monthly_salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('academic_session', models.CharField(default=core.session_utils.default_current_academic_session, max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_teacher_of', models.ForeignKey(blank=True, help_text='Leave blank if not a class teacher', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_teacher', to='core.schoolclass')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='core.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(blank=True, editable=False, max_length=20)),
                ('academic_session', models.CharField(default=core.session_utils.default_current_academic_session, max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payment_months', models.JSONField(default=list)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments_made', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='core.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='core.teacher')),
            ],
            options={
                'ordering': ['-payment_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, help_text='Meta WhatsApp Phone Number ID', max_length=80)),
                ('waba_id', models.CharField(blank=True, help_text='WhatsApp Business Account ID', max_length=80)),
                ('access_token', models.TextField(blank=True, help_text='Permanent Meta access token')),
                ('template_name', models.CharField(blank=True, default='', help_text='Pre-approved WhatsApp template name', max_length=100)),
                ('template_language', models.CharField(blank=True, default='en_US', help_text='Template language code, e.g. en_US', max_length=20)),
                ('is_active', models.BooleanField(default=False, help_text='Enable WhatsApp sending')),
                ('announcement_template_name', models.CharField(blank=True, default='', help_text='Pre-approved WhatsApp template for announcements (should have 1 body param {{1}})', max_length=100)),
                ('announcement_template_language', models.CharField(blank=True, default='en_US', help_text='Language code for announcement template, e.g. en_US', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_config', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(default=core.session_utils.default_current_academic_session, max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('frequency', models.CharField(default='monthly', max_length=20)),
                ('fee_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='core.feecategory')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='core.schoolclass')),
            ],
            options={
                'unique_together': {('school_class', 'fee_category', 'academic_session')},
            },
        ),
        migrations.CreateModel(
            name='SchoolSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(max_length=20, validators=[core.session_utils.validate_academic_session])),
                ('session_start_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='april', max_length=15)),
                ('session_end_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='march', max_length=15)),
                ('billing_start_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='april', max_length=15)),
                ('billing_end_month', models.CharField(choices=[('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December'), ('january', 'January'), ('february', 'February'), ('march', 'March')], default='march', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to='core.school')),
            ],
            options={
                'ordering': ['-academic_session', '-id'],
                'unique_together': {('school', 'academic_session')},
            },
        ),
    ]
